drop table public.comment cascade;
drop table public.post cascade;
drop table public.reaction cascade;
drop table public.user cascade;

CREATE TABLE public.COMMENT(
	ID INT NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	CONTENT TEXT,
	CREATE_AT TIMESTAMP,
	POST_ID INT,
	AUTHOR_ID INT,
	CONSTRAINT PK_COMMENT PRIMARY KEY(ID) 
);

CREATE TABLE public.POST(
	ID INT NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	AUTHOR_ID INT,
	CREATE_AT TIMESTAMP,
	TITLE VARCHAR(500),
	CONTENT TEXT,
	CONSTRAINT PK_POST PRIMARY KEY(ID) 
);
CREATE TABLE public.REACTION(
	ID INT NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	CREATE_AT TIMESTAMP,
	POST_ID INT,
	COMMENT_ID INT,
	AUTHOR_ID INT,
	CONSTRAINT PK_REACTION PRIMARY KEY(ID) 
);

CREATE TABLE public.USER (
	ID INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    fullname VARCHAR,
    dob VARCHAR,
    username VARCHAR,
    password VARCHAR,
    is_admin boolean DEFAULT false,
	CONSTRAINT PK_USER PRIMARY KEY(ID)
);
	

--
-- PostgreSQL database dump
--

-- Dumped from database version 14.4 (Ubuntu 14.4-1.pgdg20.04+1)
-- Dumped by pg_dump version 14.2

-- Started on 2022-07-10 12:41:40 +07

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4322 (class 0 OID 6659675)
-- Dependencies: 214
-- Data for Name: comment; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.comment(CONTENT ,CREATE_AT ,POST_ID ,AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('update comment test cua bai post test', '2022-05-22 10:15:06.796153+00', 1, 10);
INSERT INTO public.comment(CONTENT ,CREATE_AT ,POST_ID ,AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('test comment', '2022-06-20 20:32:20.168577+00', 10, 5);
INSERT INTO public.comment(CONTENT ,CREATE_AT ,POST_ID ,AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('test comment again', '2022-06-20 20:32:42.10532+00', 10, 5);
INSERT INTO public.comment(CONTENT ,CREATE_AT ,POST_ID ,AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ( 'test hehe', '2022-06-20 20:33:15.236251+00', 10, 5);
INSERT INTO public.comment(CONTENT ,CREATE_AT ,POST_ID ,AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('sumthing', '2022-06-20 20:34:34.230999+00', 7, 5);
INSERT INTO public.comment(CONTENT ,CREATE_AT ,POST_ID ,AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('Thú vị thật không?', '2022-06-21 01:21:25.194599+00', 7, 10);
INSERT INTO public.comment(CONTENT ,CREATE_AT ,POST_ID ,AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('Mọi người giúp đỡ nhé', '2022-06-21 01:22:28.156438+00', 11, 8);
INSERT INTO public.comment(CONTENT ,CREATE_AT ,POST_ID ,AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('Ok anh bạn, tôi có thể giúp anh', '2022-06-21 01:23:20.960481+00', 11, 9);
INSERT INTO public.comment(CONTENT ,CREATE_AT ,POST_ID ,AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('Vào đây nhé: https://github.com/', '2022-06-21 01:23:47.170378+00', 11, 10);
INSERT INTO public.comment(CONTENT ,CREATE_AT ,POST_ID ,AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('hi', '2022-06-22 11:57:46.125298+00', 10, 2);
INSERT INTO public.comment(CONTENT ,CREATE_AT ,POST_ID ,AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('ok bạn nha', '2022-06-22 13:26:04.394191+00', 11, 2);
INSERT INTO public.comment(CONTENT ,CREATE_AT ,POST_ID ,AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('Xin chào bạn', '2022-06-22 13:26:45.791661+00', 12, 2);
INSERT INTO public.comment(CONTENT ,CREATE_AT ,POST_ID ,AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('hey hey', '2022-06-24 16:20:24.685934+00', 1, 3);
INSERT INTO public.comment(CONTENT ,CREATE_AT ,POST_ID ,AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('chào cậu', '2022-06-24 16:20:53.18751+00', 12, 4);
INSERT INTO public.comment(CONTENT ,CREATE_AT ,POST_ID ,AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('hehehe', '2022-07-06 07:54:10.585113+00', 8, 5);
INSERT INTO public.comment(CONTENT ,CREATE_AT ,POST_ID ,AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('yeah', '2022-07-06 07:56:12.439114+00', 8, 6);
INSERT INTO public.comment(CONTENT ,CREATE_AT ,POST_ID ,AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('ok nhe1', '2022-07-06 08:12:08.487732+00', 11, 7);
INSERT INTO public.comment(CONTENT ,CREATE_AT ,POST_ID ,AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('thu vi that', '2022-07-06 08:12:58.077903+00', 7, 8);
INSERT INTO public.comment(CONTENT ,CREATE_AT ,POST_ID ,AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('ok', '2022-07-06 08:42:25.049082+00', 12, 9);


--
-- TOC entry 4320 (class 0 OID 6659584)
-- Dependencies: 212
-- Data for Name: post; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.post(AUTHOR_ID ,CREATE_AT ,TITLE ,CONTENT) OVERRIDING SYSTEM VALUE VALUES (1, '2022-05-22 10:11:37.362143+00', 'Update bai post test', 'post test');
INSERT INTO public.post(AUTHOR_ID ,CREATE_AT ,TITLE ,CONTENT) OVERRIDING SYSTEM VALUE VALUES (5, '2022-06-20 19:43:37.699466+00', 'test content third', 'test third');
INSERT INTO public.post(AUTHOR_ID ,CREATE_AT ,TITLE ,CONTENT) OVERRIDING SYSTEM VALUE VALUES (5, '2022-06-20 19:49:55.707322+00', 'content fourth', 'test fourth');
INSERT INTO public.post(AUTHOR_ID ,CREATE_AT ,TITLE ,CONTENT) OVERRIDING SYSTEM VALUE VALUES (5, '2022-06-20 20:01:47.574161+00', 'Chủ đề này sẽ rất thú vị nếu bạn thích', 'Chủ đề thú vị');
INSERT INTO public.post(AUTHOR_ID ,CREATE_AT ,TITLE ,CONTENT) OVERRIDING SYSTEM VALUE VALUES (6, '2022-06-20 20:03:44.043937+00', 'test nữa nè', 'test nữa');
INSERT INTO public.post(AUTHOR_ID ,CREATE_AT ,TITLE ,CONTENT) OVERRIDING SYSTEM VALUE VALUES (5, '2022-06-20 20:18:20.021656+00', 'test hehee', 'test cái nữa');
INSERT INTO public.post(AUTHOR_ID ,CREATE_AT ,TITLE ,CONTENT) OVERRIDING SYSTEM VALUE VALUES (4, '2022-06-21 01:22:10.59482+00', 'Nghe nói phim này khá hay, chỉ là tôi không nhớ nội dung', 'Có ai giúp tôi kiếm phim được không?');
INSERT INTO public.post(AUTHOR_ID ,CREATE_AT ,TITLE ,CONTENT) OVERRIDING SYSTEM VALUE VALUES (4, '2022-06-22 13:26:29.373458+00', 'Hello everyone', 'Xin chào mọi người');
INSERT INTO public.post(AUTHOR_ID ,CREATE_AT ,TITLE ,CONTENT) OVERRIDING SYSTEM VALUE VALUES (10, '2022-07-06 07:53:54.405883+00', 'Chao moi nguoi', 'Hi everyone');
INSERT INTO public.post(AUTHOR_ID ,CREATE_AT ,TITLE ,CONTENT) OVERRIDING SYSTEM VALUE VALUES (10, '2022-07-06 07:56:03.279058+00', 'hello', 'hihi');
INSERT INTO public.post(AUTHOR_ID ,CREATE_AT ,TITLE ,CONTENT) OVERRIDING SYSTEM VALUE VALUES (9, '2022-07-06 07:56:19.888138+00', 'tét', 'tét');
INSERT INTO public.post(AUTHOR_ID ,CREATE_AT ,TITLE ,CONTENT) OVERRIDING SYSTEM VALUE VALUES (8, '2022-07-06 08:41:42.836031+00', 'xin chao', 'xin chao');


--
-- TOC entry 4324 (class 0 OID 6659693)
-- Dependencies: 216
-- Data for Name: reaction; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.reaction(CREATE_AT ,POST_ID ,COMMENT_ID ,AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('2022-06-22 11:54:38.10964+00', 11,NULL, 1);
INSERT INTO public.reaction(CREATE_AT ,POST_ID ,COMMENT_ID ,AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('2022-06-22 11:55:01.720961+00', 11,NULL, 2);
INSERT INTO public.reaction(CREATE_AT ,POST_ID ,COMMENT_ID ,AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('2022-06-22 11:57:42.87093+00', 10,NULL, 3);
INSERT INTO public.reaction(CREATE_AT ,POST_ID ,COMMENT_ID ,AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('2022-06-22 13:25:56.893009+00', NULL,3, 4);
INSERT INTO public.reaction(CREATE_AT ,POST_ID ,COMMENT_ID ,AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('2022-06-22 13:26:41.12704+00', NULL,4, 5);
INSERT INTO public.reaction(CREATE_AT ,POST_ID ,COMMENT_ID ,AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('2022-06-24 16:20:42.734435+00', 1,NULL, 6);
INSERT INTO public.reaction(CREATE_AT ,POST_ID ,COMMENT_ID ,AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('2022-06-24 16:20:56.718172+00', 12,NULL, 7);
INSERT INTO public.reaction(CREATE_AT ,POST_ID ,COMMENT_ID ,AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('2022-07-06 07:54:15.706904+00', 12,NULL, 8);
INSERT INTO public.reaction(CREATE_AT ,POST_ID ,COMMENT_ID ,AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('2022-07-06 07:55:21.330748+00', 12,NULL, 9);
INSERT INTO public.reaction(CREATE_AT ,POST_ID ,COMMENT_ID ,AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('2022-07-06 08:06:25.470232+00', 11,NULL, 10);


--
-- TOC entry 4318 (class 0 OID 6659572)
-- Dependencies: 210
-- Data for Name: user; Type: TABLE DATA; Schema: public; Owner: -
--


INSERT INTO public."user"(fullname ,dob ,username ,password,is_admin) OVERRIDING SYSTEM VALUE VALUES ('Hoang Thi Truong', '12/02/2002', 'test4', '$2b$10$IehL4ShtGLCv5OAUUY7ELeyh2xrJBwc.DmNg0hmkXmMOphK1f5Cda', false);
INSERT INTO public."user"(fullname ,dob ,username ,password,is_admin) OVERRIDING SYSTEM VALUE VALUES ('Manh Hung Tien', '12/02/2002', 'test5', '$2b$10$9u6vSvL4Df0JhVlzFeaJi.32blRSoJrsA.w1vDcBIUdl/XF32DJI2', false);
INSERT INTO public."user"(fullname ,dob ,username ,password,is_admin) OVERRIDING SYSTEM VALUE VALUES ('Nguyen Huy Hoang', '12/02/2002', 'hhoang', '$2b$10$Vnw0j.qQWa/ap5JUGViiwexqqVYbyF9BqvAhqY.lQrn2iv/maaiIK', false);
INSERT INTO public."user"(fullname ,dob ,username ,password,is_admin) OVERRIDING SYSTEM VALUE VALUES ('Minh Lap', '12/02/2002', 'minhlap', '$2b$10$GRdmekQQMLY5i.dAmmMnzOaoFtLkOC7fvJ/IWjmqVNB.d/ZJH..P.', false);
INSERT INTO public."user"(fullname ,dob ,username ,password,is_admin) OVERRIDING SYSTEM VALUE VALUES ('Nguyen Hoang Tien', '12/02/2001', 'htien2', '$2b$10$EuwgrUkd2rO6czKdZn0HA.EjESm7I07Rgh0hGHjEy/Ojm//riCuNi', false);
INSERT INTO public."user"(fullname ,dob ,username ,password,is_admin) OVERRIDING SYSTEM VALUE VALUES ('Ngo Nhat Tho', '12/02/2001', 'htien3', '$2b$10$oHbZVlTGywSgyFea.hAFoOOwIY6gEFR7a0tsjOLu2Fu3hpaW3VecC', false);
INSERT INTO public."user"(fullname ,dob ,username ,password,is_admin) OVERRIDING SYSTEM VALUE VALUES ('Le Duc Tam', '12/02/2003', 'tamld', '$2b$10$3iwrwkqLJyWhMqN7bci6b.yYvaxlT.2jw5k6KXwNbicupDuS/Z6Xe', false);
INSERT INTO public."user"(fullname ,dob ,username ,password,is_admin) OVERRIDING SYSTEM VALUE VALUES ('staff1', '1/1/2000', 'staff1', '$2b$10$7xcP0dWZEW2TsgUPUQYeZ.bsiIObiKS7a.QbJtCGcZJlu.pNPbLYS', false);
INSERT INTO public."user"(fullname ,dob ,username ,password,is_admin) OVERRIDING SYSTEM VALUE VALUES ('Hoang Vinh', '12/02/2002', 'hvinh', '$2b$10$AyDNQxgV7i0HLnkUMjE2aOOz9CD3Jc0PNKivGQOG1AP8SeB9hJKbu', false);
INSERT INTO public."user"(fullname ,dob ,username ,password,is_admin) OVERRIDING SYSTEM VALUE VALUES ('leduc tam', '11/02/2001', 'godofwar', '$2a$10$1eY0TesxaS2Pd8SRh5ntdOCazK869VQCDK0AF/wE2fpMtUikUV5ye', false);


--
-- TOC entry 4330 (class 0 OID 0)
-- Dependencies: 213
-- Name: comment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.comment_id_seq', 19, true);


--
-- TOC entry 4331 (class 0 OID 0)
-- Dependencies: 211
-- Name: post_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.post_id_seq', 16, true);


--
-- TOC entry 4332 (class 0 OID 0)
-- Dependencies: 215
-- Name: reaction_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.reaction_id_seq', 42, true);


--
-- TOC entry 4333 (class 0 OID 0)
-- Dependencies: 209
-- Name: user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.user_id_seq', 44, true);


-- Completed on 2022-07-10 12:42:13 +07

--
-- PostgreSQL database dump complete
--


